### ISSUE TITLE
Subtest support

### ISSUE THREAD

**Issue by elementbound** [dmaevsky/utap#3]
Hi,

I've tried utap with the `describe`/`it` syntax, but unfortunately this is how it displays a failure:
```
  ❌ /mnt/e/dev/js/nlon/test/server.test.mjs
          duration_ms: 356.7718
          failureType: 'subtestsFailed'
          exitCode: 1
          error: 'test failed'
          code: 'ERR_TEST_FAILURE'
```

While it displays the file itself, the subtests are missing. For reference, here's a [test](https://github.com/elementbound/nlon/blob/39e22bde9aedd109ef017c46d2e8fec5ff634e89/test/server/response.test.mjs) to show what I'm running utap against.

tl;dr: Please add subtest support, thanks a lot in advance!

**Comment by dmaevsky** [comment]
Added support in commit 6f72c9d (v0.2.0)
